# Generated by Django 2.2 on 2020-02-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This name is for internal purpose and cannot be changed', max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('content', models.TextField(verbose_name='HTML content of agreement')),
            ],
        ),
        migrations.CreateModel(
            name='UserSignedAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='User first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='User last name')),
                ('street', models.CharField(max_length=255, verbose_name='User street')),
                ('postcode', models.CharField(max_length=255, verbose_name='User postcode')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terms.AgreementTemplate')),
            ],
        ),
    ]
